version: '3'
services:
  mysql:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root-password"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "db_conn"
      MYSQL_PASSWORD: "db-password"
    volumes:
      - /data/dbs/mysql:/var/lib/mysql:rw
    networks:
      back:
        ipv4_address: 10.10.0.10
    command:
      "--character-set-server=utf8 --collation-server=utf8_unicode_ci"

  mysql_web:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      front:
        ipv4_address: 172.16.0.250
      back:
        ipv4_address: 10.10.0.250
    depends_on:
      - mysql
    links:
      - mysql

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
