version: '3'

networks:
    kafka-net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.10.0/28

services:
    zookeeper:
        image: zookeeper:3.4
        container_name: zookeeper
        restart: always
        networks:
            - kafka-net
        #ports:
        #    - 2181:2181
        volumes:
          - /data/dbs/zookeeper:/data
          - /data/logs/zookeeper:/datalog

    kafka:
        image: ches/kafka:latest
        container_name: kafka
        restart: on-failure:10
        networks:
            - kafka-net
        ports:
            - 9092:9092
        depends_on:
            - zookeeper
        environment:
            ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
            KAFKA_BROKER_ID: 11
            KAFKA_PORT: 9092
            KAFKA_NUM_PARTITIONS: 4
            KAFKA_LOG_RETENTION_HOURS: 96
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
